/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tobalation (https://sketchfab.com/tobalation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-3a496376915846459d77fc14fdd6c1e0
Title: Retro computer
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

const Computer = (props: Partial<THREE.Group>) => {
  const { nodes, materials } = useGLTF('/retro_computer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.364}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_4 as THREE.Mesh).geometry}
            material={materials.TextureGrid}
            position={[0, 0, -0.031]}
            rotation={[0.087, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_6 as THREE.Mesh).geometry}
            material={materials.TextureGrid}
            position={[0, 0.5, 0.031]}
            rotation={[0.087, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_8 as THREE.Mesh).geometry}
            material={materials.TextureGrid}
            position={[0.875, 0.063, 0.75]}
            rotation={[0.087, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_10 as THREE.Mesh).geometry}
            material={materials.TextureGrid}
            position={[0, 0.062, 0.813]}
            rotation={[0.087, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/retro_computer.glb')

export default Computer;
