/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: arloopa (https://sketchfab.com/arloopa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dalithe-persistence-of-memory-ab3e99facbdb4d9d8661d3f07815638e
Title: Dali,The Persistence of Memory
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export const Memory = (props: Partial<THREE.Object3D>) => {
  const { nodes, materials } = useGLTF('/dalithe_persistence_of_memory.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Extract2_04_-_Default_0'] as THREE.Mesh).geometry}
        material={materials['04_-_Default']}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cylinder006_Ceramic_0 as THREE.Mesh).geometry}
        material={materials.Ceramic}
        position={[0.541, 0, 2.543]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Box001_05_-_Default_0'] as THREE.Mesh).geometry}
        material={materials['05_-_Default']}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Line005_02_-_Default_0'] as THREE.Mesh).geometry}
        material={materials['02_-_Default']}
        position={[0, 0.005, 0]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Cylinder003_01_-_Default_0'] as THREE.Mesh).geometry}
        material={materials['01_-_Default']}
        position={[-0.584, 0.659, -1.595]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Sphere003_03_-_Default_0'] as THREE.Mesh).geometry}
        material={materials['03_-_Default']}
        position={[-0.901, 0.331, -1.311]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Line004_16_-_Matte_Plastic_0'] as THREE.Mesh).geometry}
        material={materials['16_-_Matte_Plastic']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cylinder007_Ceramic1_0 as THREE.Mesh).geometry}
        material={materials.Ceramic1}
        position={[0.541, 0, 2.543]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.022}
      />
    </group>
  )
}

useGLTF.preload('/dalithe_persistence_of_memory.glb')
