/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: betocarrillo (https://sketchfab.com/betocarrillo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/wanderer-above-the-sea-of-fog-518e605e9b734c86aab5bc22f9797f77
Title: Wanderer above the sea of fog
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function Wanderer(props: Partial<THREE.Object3D>) {
  const { nodes, materials } = useGLTF('/wanderer_above_the_sea_of_fog.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.676}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_4 as THREE.Mesh).geometry}
            material={materials.brush_Ink}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_6 as THREE.Mesh).geometry}
            material={materials.brush_Ink}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_8 as THREE.Mesh).geometry}
            material={materials.brush_Ink}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_10 as THREE.Mesh).geometry}
            material={materials.brush_ThickPaint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_12 as THREE.Mesh).geometry}
            material={materials.brush_Marker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object_14 as THREE.Mesh).geometry}
            material={
              materials['media_image_Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog']
            }
            position={[-11.413, 3.033, 16.793]}
            rotation={[0.082, -0.72, 0.054]}
            scale={53.755}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wanderer_above_the_sea_of_fog.glb')