/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export function Tea(props: any) {
  const { nodes, materials } = useGLTF('/fiesta_tea-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_28 as THREE.Mesh).geometry}
        material={materials.peripheri_Base_Color}
        position={[-0.238, 1, 0.665]}
        scale={0.625}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_26 as THREE.Mesh).geometry}
        material={materials.trad_edges}
        position={[0, 0.316, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_30 as THREE.Mesh).geometry}
        material={materials['table_Base_Color.002']}
        position={[0, 0.316, 0]}
        scale={0.69}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_14 as THREE.Mesh).geometry}
        material={materials.teapot_glass_Base_Color}
        position={[-0.908, 1.351, 0.038]}
      />
    </group>
  )
}

// useGLTF.preload('/fiesta_tea-transformed.glb')

export default Tea;

